create table account_balance (
    id bigint generated by default as identity primary key,
    account_no varchar(32) not null,
    customer_id varchar(64) not null,
    owner_name varchar(120) not null,
    user_region varchar(32) not null,
    account_type varchar(32) not null,
    currency varchar(3) not null,
    available_balance decimal(19, 4) not null,
    frozen_balance decimal(19, 4) not null,
    status varchar(32) not null,
    version bigint,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_account_balance_account_no unique (account_no)
);

create table ledger_entry (
    id bigint generated by default as identity primary key,
    entry_no varchar(40) not null,
    transaction_no varchar(40) not null,
    account_no varchar(32) not null,
    direction varchar(16) not null,
    amount decimal(19, 4) not null,
    balance_after decimal(19, 4) not null,
    currency varchar(3) not null,
    entry_type varchar(40) not null,
    created_at timestamp not null,
    constraint uk_ledger_entry_entry_no unique (entry_no)
);

create index idx_ledger_entry_transaction_no on ledger_entry (transaction_no);
create index idx_ledger_entry_account_created on ledger_entry (account_no, created_at);

create table transfer_order (
    id bigint generated by default as identity primary key,
    order_no varchar(40) not null,
    request_id varchar(80) not null,
    from_account_no varchar(32) not null,
    to_account_no varchar(32) not null,
    amount decimal(19, 4) not null,
    fee decimal(19, 4) not null,
    currency varchar(3) not null,
    status varchar(32) not null,
    risk_code varchar(80),
    failure_reason varchar(500),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_transfer_order_order_no unique (order_no)
);

create index idx_transfer_order_request_id on transfer_order (request_id);
create index idx_transfer_order_from_created on transfer_order (from_account_no, created_at);
create index idx_transfer_order_to_created on transfer_order (to_account_no, created_at);

create table remittance_order (
    id bigint generated by default as identity primary key,
    order_no varchar(40) not null,
    request_id varchar(80) not null,
    sender_account_no varchar(32) not null,
    receiver_account_no varchar(32) not null,
    source_amount decimal(19, 4) not null,
    exchange_rate decimal(19, 8) not null,
    fee decimal(19, 4) not null,
    target_amount decimal(19, 4) not null,
    source_currency varchar(3) not null,
    target_currency varchar(3) not null,
    destination_country varchar(2) not null,
    swift_code varchar(32),
    iban varchar(40),
    status varchar(32) not null,
    risk_code varchar(80),
    failure_reason varchar(500),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_remittance_order_order_no unique (order_no)
);

create index idx_remittance_order_request_id on remittance_order (request_id);
create index idx_remittance_order_sender_created on remittance_order (sender_account_no, created_at);

create table idempotency_record (
    id bigint generated by default as identity primary key,
    request_id varchar(80) not null,
    business_type varchar(40) not null,
    business_no varchar(32) not null,
    status varchar(32) not null,
    created_at timestamp not null,
    constraint uk_idempotency_request_business unique (request_id, business_type)
);

create table audit_log (
    id bigint generated by default as identity primary key,
    business_no varchar(40) not null,
    action varchar(40) not null,
    result varchar(32) not null,
    detail varchar(500),
    created_at timestamp not null
);

create index idx_audit_log_business_no on audit_log (business_no);

create table outbox_event (
    id bigint generated by default as identity primary key,
    event_id varchar(80) not null,
    aggregate_id varchar(80) not null,
    event_type varchar(120) not null,
    payload clob not null,
    status varchar(32) not null,
    created_at timestamp not null
);

create index idx_outbox_event_status_created on outbox_event (status, created_at);
