create table customer_profile (
    id bigint generated by default as identity primary key,
    customer_id varchar(64) not null,
    full_name varchar(120) not null,
    user_region varchar(32) not null,
    country_code varchar(2) not null,
    phone varchar(32),
    email varchar(120),
    risk_level varchar(32) not null,
    status varchar(32) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_customer_profile_customer_id unique (customer_id)
);

create table kyc_profile (
    id bigint generated by default as identity primary key,
    customer_id varchar(64) not null,
    document_type varchar(32) not null,
    masked_document_no varchar(64) not null,
    kyc_level varchar(32) not null,
    status varchar(32) not null,
    reviewed_by varchar(64),
    reviewed_at timestamp,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_kyc_profile_customer_id unique (customer_id)
);

create table fee_rule (
    id bigint generated by default as identity primary key,
    rule_code varchar(40) not null,
    business_type varchar(40) not null,
    source_currency varchar(3) not null,
    target_currency varchar(3) not null,
    fee_rate decimal(10, 6) not null,
    min_fee decimal(19, 4) not null,
    max_fee decimal(19, 4) not null,
    status varchar(32) not null,
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_fee_rule_code unique (rule_code)
);

create table exchange_rate (
    id bigint generated by default as identity primary key,
    rate_code varchar(40) not null,
    source_currency varchar(3) not null,
    target_currency varchar(3) not null,
    rate decimal(19, 8) not null,
    provider varchar(64) not null,
    status varchar(32) not null,
    effective_at timestamp not null,
    expires_at timestamp,
    created_at timestamp not null,
    constraint uk_exchange_rate_code unique (rate_code)
);

create table reversal_order (
    id bigint generated by default as identity primary key,
    reversal_no varchar(40) not null,
    original_order_no varchar(40) not null,
    request_id varchar(80) not null,
    amount decimal(19, 4) not null,
    currency varchar(3) not null,
    status varchar(32) not null,
    reason varchar(500),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint uk_reversal_order_no unique (reversal_no),
    constraint uk_reversal_original_order_no unique (original_order_no)
);

create index idx_customer_profile_region_status on customer_profile (user_region, status);
create index idx_kyc_profile_status on kyc_profile (status);
create index idx_exchange_rate_pair_status on exchange_rate (source_currency, target_currency, status);
create index idx_fee_rule_business_pair on fee_rule (business_type, source_currency, target_currency, status);

insert into customer_profile (
    customer_id, full_name, user_region, country_code, phone, email, risk_level, status, created_at, updated_at
) values
('C_DEMO_001', 'Zhang San Demo', 'DOMESTIC', 'CN', '+8613800000001', 'zhang.demo@example.com', 'LOW', 'ACTIVE', current_timestamp, current_timestamp),
('C_DEMO_002', 'Li Si Demo', 'DOMESTIC', 'CN', '+8613800000002', 'li.demo@example.com', 'LOW', 'ACTIVE', current_timestamp, current_timestamp),
('U_DEMO_001', 'Alice Smith Demo', 'OVERSEAS', 'US', '+12025550101', 'alice.demo@example.com', 'MEDIUM', 'ACTIVE', current_timestamp, current_timestamp),
('U_DEMO_002', 'Bob Wilson Demo', 'OVERSEAS', 'US', '+12025550102', 'bob.demo@example.com', 'MEDIUM', 'ACTIVE', current_timestamp, current_timestamp);

insert into kyc_profile (
    customer_id, document_type, masked_document_no, kyc_level, status, reviewed_by, reviewed_at, created_at, updated_at
) values
('C_DEMO_001', 'NATIONAL_ID', '110***********001', 'STANDARD', 'APPROVED', 'system', current_timestamp, current_timestamp, current_timestamp),
('C_DEMO_002', 'NATIONAL_ID', '110***********002', 'STANDARD', 'APPROVED', 'system', current_timestamp, current_timestamp, current_timestamp),
('U_DEMO_001', 'PASSPORT', 'P********001', 'ENHANCED', 'APPROVED', 'system', current_timestamp, current_timestamp, current_timestamp),
('U_DEMO_002', 'PASSPORT', 'P********002', 'STANDARD', 'PENDING', null, null, current_timestamp, current_timestamp);

insert into fee_rule (
    rule_code, business_type, source_currency, target_currency, fee_rate, min_fee, max_fee, status, created_at, updated_at
) values
('FEE_RM_CNY_USD', 'INTERNATIONAL_REMITTANCE', 'CNY', 'USD', 0.003000, 1.0000, 200.0000, 'ACTIVE', current_timestamp, current_timestamp),
('FEE_RM_USD_CNY', 'INTERNATIONAL_REMITTANCE', 'USD', 'CNY', 0.003000, 2.0000, 300.0000, 'ACTIVE', current_timestamp, current_timestamp);

insert into exchange_rate (
    rate_code, source_currency, target_currency, rate, provider, status, effective_at, expires_at, created_at
) values
('FX_CNY_USD_DEMO', 'CNY', 'USD', 0.14000000, 'DEMO_PROVIDER', 'ACTIVE', current_timestamp, null, current_timestamp),
('FX_USD_CNY_DEMO', 'USD', 'CNY', 7.20000000, 'DEMO_PROVIDER', 'ACTIVE', current_timestamp, null, current_timestamp);
