create table remittance_quote (
    id bigint generated by default as identity primary key,
    quote_id varchar(40) not null,
    source_currency varchar(3) not null,
    target_currency varchar(3) not null,
    source_amount decimal(19, 4) not null,
    exchange_rate decimal(19, 8) not null,
    fee decimal(19, 4) not null,
    target_amount decimal(19, 4) not null,
    fee_rule_code varchar(40) not null,
    rate_code varchar(40) not null,
    status varchar(32) not null,
    expires_at timestamp not null,
    created_at timestamp not null,
    constraint uk_remittance_quote_quote_id unique (quote_id)
);

alter table remittance_order add column quote_id varchar(40);
alter table remittance_order add column fee_rule_code varchar(40);
alter table remittance_order add column rate_code varchar(40);

alter table outbox_event add column retry_count int not null default 0;
alter table outbox_event add column last_error varchar(500);
alter table outbox_event add column published_at timestamp;
alter table outbox_event add column updated_at timestamp;

alter table idempotency_record add column response_snapshot clob;
alter table idempotency_record add column updated_at timestamp;

update outbox_event set updated_at = created_at where updated_at is null;
update idempotency_record set updated_at = created_at where updated_at is null;

create index idx_remittance_quote_status_expires on remittance_quote (status, expires_at);
